### ISSUE TITLE
syncRandom() throwing validation error

### ISSUE THREAD

**Issue by dmr07** [matomesc/mongoose-random#10]
Error below:

```
ValidationError: user validation failed
    at MongooseError.ValidationError (/home/vagrant/local/venvy-eva/node_modules/mongoose/lib/error/validation.js:22:11)
    at model.Document.invalidate (/home/vagrant/local/venvy-eva/node_modules/mongoose/lib/document.js:1355:32)
    at init (/home/vagrant/local/venvy-eva/node_modules/mongoose/lib/document.js:337:18)
    at init (/home/vagrant/local/venvy-eva/node_modules/mongoose/lib/document.js:328:7)
    at init (/home/vagrant/local/venvy-eva/node_modules/mongoose/lib/document.js:328:7)
    at model.Document.init (/home/vagrant/local/venvy-eva/node_modules/mongoose/lib/document.js:289:3)
...
```

Schema Declaration: 

```
var userSchema =  new mongoose.Schema({ ... });
// For pulling random documents - https://github.com/matomesc/mongoose-random
userSchema.plugin(random, { path: 'r' });

var user    = mongoose.model('user', userSchema)

user.syncRandom(function (err, result) {
  if (err) return console.log(err);
  console.log(result.updated);
});
```

Any help is appreciated, thanks.

**Comment by dmr07** [comment]
Turns out one of the documents carried an invalid key-value pair. Resolved the error and `syncRandom()` is now working.
